spring.application.name=markdown-to-pdf

# Koneksi ke DataBase PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/markdowndb
spring.datasource.username=postgres
spring.datasource.password=postgres

# Spring Boot otomatis bikin tabel ketika pertama kali di run
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
